name: ntsapp
description: "Note to Self v2.0 - Note Safe - Encrypted notes"
publish_to: 'none'
version: 2.0.13+59

environment:
  sdk: ^3.5.1

dependencies:
  archive: ^3.6.1
  audioplayers: ^6.1.0
  bip39: ^1.0.6
  change_app_package_name: ^1.4.0
  chewie: ^1.8.5
  crypto: ^3.0.6
  device_info_plus: ^11.3.0
  encrypt: ^5.0.3
  file_picker: ^8.1.3
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.9+2
  flutter_launcher_icons: ^0.14.1
  flutter_local_notifications: ^19.0.0
  flutter_map: ^7.0.2
  flutter_native_splash: ^2.4.3
  flutter_secure_storage: ^9.2.4
  geolocator: ^13.0.1
  hive_flutter: ^1.1.0
  http: ^1.2.2
  image: ^4.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  latlong2: ^0.9.1
  local_auth: ^2.3.0
  lucide_icons: ^0.257.0
  media_kit: ^1.1.11
  media_kit_libs_video: ^1.0.5
  media_kit_video: ^1.2.5
  metadata_fetch: ^0.4.2
  mime: ^2.0.0
  open_filex: ^4.6.0
  package_info_plus: ^8.1.0
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  provider: ^6.1.2
  purchases_flutter: ^8.6.1
  random_string: ^2.3.1
  receive_sharing_intent: ^1.8.1
  record: ^5.2.0
  scrollable_positioned_list: ^0.3.8
  sentry_flutter: ^8.10.1
  share_plus: ^10.1.2
  siri_wave: ^2.1.0
  sodium_libs: ^3.4.3
  sqflite: ^2.4.0
  sqflite_common_ffi: ^2.3.4
  supabase_flutter: ^2.8.3
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  video_player: ^2.9.2
  window_size: ^0.1.0
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Medium.ttf
        - asset: fonts/Inter-Light.ttf
        - asset: fonts/Inter-SemiBold.ttf
        - asset: fonts/Inter-Bold.ttf

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter_native_splash:
  android: true
  ios: false
  web: false
  image: assets/splash.png
  color: "#16161A"
  android_12:
    image: assets/splash.png
    color: "#16161A"