name: ntsapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  change_app_package_name: ^1.4.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  image: ^4.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  mime: ^2.0.0
  package_info_plus: ^8.1.0
  path: ^1.9.0
  path_provider: ^2.1.5
  sqflite: ^2.4.0
  sqflite_common_ffi: ^2.3.4
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
