name: ntsapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.6.5

environment:
  sdk: ^3.5.1

dependencies:
  archive: ^3.6.1
  audioplayers: ^6.1.0
  change_app_package_name: ^1.4.0
  file_picker: ^8.1.3
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.9+2
  flutter_launcher_icons: ^0.14.1
  flutter_map: ^7.0.2
  geolocator: ^13.0.1
  image: ^4.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  latlong2: ^0.9.1
  mime: ^2.0.0
  open_filex: ^4.5.0
  package_info_plus: ^8.1.0
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  record: ^5.2.0
  share_plus: ^10.1.2
  siri_wave: ^2.1.0
  sqflite: ^2.4.0
  sqflite_common_ffi: ^2.3.4
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "splash"
  ios: false
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false