display_name: NoteSafe
icon: assets/icon_512.png
summary: A privacy focused note taking app with a chat like interface.
group: Applications
vendor: Phone Safe Inc.
packager: Jeevan Singh
packagerEmail: getphonesafe@gmail.com
license: AGPLv3
url: https://github.com/jeerovan/ntsapp
requires:
  - pulseaudio-utils
  - ffmpeg-free
  - openh264
  - mozilla-openh264
  - gstreamer1
  - gstreamer1-plugins-base
  - gstreamer1-plugins-good
  - gstreamer1-plugins-bad-free
  - gstreamer1-libav
  - libsecret
  - jsoncpp
  - libsodium
  - mpv
  - mpv-libs
  - sqlite-libs
keywords:
  - NoteSafe
generic_name: Note Application
categories:
  - Utility
startup_notify: true
